drop table if exists book;
drop table if exists person;

create table person
(
    id int generated by default as identity primary key,
    full_name varchar(70) not null unique,
    birth_year int not null check (birth_year >= 1900),
    email varchar(100) not null unique
);

create table book
(
    id int generated by default as identity primary key,
    title varchar(70) not null,
    author varchar(70) not null,
    published_year int,
    person_id int references person on delete set null
);