drop table if exists book;
drop table if exists person;

create table person
(
    id int generated by default as identity primary key,
    full_name varchar(70) not null,
    birthday date not null check (birthday >= '1900-01-01'),
    email varchar(100) not null unique,
    created_at timestamp default now()
);

create table book
(
    id int generated by default as identity primary key,
    title varchar(70) not null,
    author varchar(70) not null,
    published int,
    person_id int references person on delete set null,
    taken_at date
);